sudo: false
language: node_js
node_js:
  - 9

branches:
  only:
    - master




#dist: trusty
#sudo: required
#language: bash

#before_install:
#  - curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh | bash
